export const Gender: { [key: number]: string } = {
  0: 'Nam',
  1: 'Nữ',
  2: 'Giới tính khác',
};

export enum UserRoles {
  STUDENT,
  ADMIN,
}

export const StudentMajor: { [key: string]: string } = {
  SOFTWARE_ENGINEERING: 'Kỹ thuật phần mềm',
  COMPUTER_SCIENCE: 'Khoa học máy tính',
  INFORMATION_TECHNOLOGY: 'Công nghệ thông tin',
  OTHER: 'Chuyên ngành khác',
};
export const City: { [key: string]: string } = {
  CAN_THO: 'Can Tho',
  DA_NANG: 'Da Nang',
  HAI_PHONG: 'Hai Phong',
  HA_NOI: 'Ha Noi',
  HO_CHI_MINH: 'Ho Chi Minh',
  BA_RIA: 'Ba Ria',
  BAC_LIEU: 'Bac Lieu',
  BAC_GIANG: 'Bac Giang',
  BAC_NINH: 'Bac Ninh',
  BAO_LOC: 'Bao Loc',
  BIEN_HOA: 'Bien Hoa',
  BEN_TRE: 'Ben Tre',
  BUON_MA_THUOT: 'Buon Ma Thuot',
  CA_MAU: 'Ca Mau',
  CAM_PHA: 'Cam Pha',
  CAO_LANH: 'Cao Lanh',
  CHAU_DOC: 'Chau Doc',
  DA_LAT: 'Da Lat',
  DIEN_BIEN_PHU: 'Dien Bien Phu',
  DONG_HA: 'Dong Ha',
  DONG_HOI: 'Dong Hoi',
  HA_TINH: 'Ha Tinh',
  HA_LONG: 'Ha Long',
  HAI_DUONG: 'Hai Duong',
  HOA_BINH: 'Hoa Binh',
  HOI_AN: 'Hoi An',
  HUE: 'Hue',
  HUNG_YEN: 'Hung Yen',
  KON_TUM: 'Kon Tum',
  LANG_SON: 'Lang Son',
  LAO_CAI: 'Lao Cai',
  LONG_XUYEN: 'Long Xuyen',
  MONG_CAI: 'Mong Cai',
  MY_THO: 'My Tho',
  NAM_DINH: 'Nam Dinh',
  NINH_BINH: 'Ninh Binh',
  NHA_TRANG: 'Nha Trang',
  CAM_RANH: 'Cam Ranh',
  PHAN_RANG_THAP_CHAM: 'Phan Rang–Thap Cham',
  PHAN_THIET: 'Phan Thiet',
  PHU_LY: 'Phu Ly',
  PLEIKU: 'Pleiku',
  QUANG_NGAI: 'Quang Ngai',
  QUY_NHON: 'Quy Nhon',
  RACH_GIA: 'Rach Gia',
  SA_DEC: 'Sa Dec',
  SOC_TRANG: 'Soc Trang',
  SON_LA: 'Son La',
  TAM_KY: 'Tam Ky',
  TAN_AN: 'Tan An',
  THAI_BINH: 'Thai Binh',
  THAI_NGUYEN: 'Thai Nguyen',
  THANH_HOA: 'Thanh Hoa',
  TRA_VINH: 'Tra Vinh',
  TUY_HOA: 'Tuy Hoa',
  TUYEN_QUANG: 'Tuyen Quang',
  UONG_BI: 'Uong Bi',
  VIET_TRI: 'Viet Tri',
  VINH: 'Vinh',
  VINH_YEN: 'Vinh Yen',
  VINH_LONG: 'Vinh Long',
  VUNG_TAU: 'Vung Tau',
  YEN_BAI: 'Yen Bai',
  CAO_BANG: 'Cao Bang',
};
export const Language: { [key: string]: string } = {
  VIETNAMESE: 'Vietnamese',
  ENGLISH: 'English',
  JAPANESE: 'Japanese',
  KOREAN: 'Korean',
  RUSSIAN: 'Russian',
  CHINESE: 'Chinese',
  SPANISH: 'Spanish',
};
export const Skills: { [key: string]: string } = {
  HTML: 'HTML',
  CSS: 'CSS',
  JAVASCRIPT: 'JavaScript',
  TYPESCRIPT: 'TypeScript',
  REACTJS: 'ReactJS',
  REACT_NATIVE: 'React Native',
  NODEJS: 'NodeJS',
  EXPRESSJS: 'ExpressJS',
  MONGODB: 'MongoDB',
  MYSQL: 'MySQL',
  POSTGRESQL: 'PostgreSQL',
  PHP: 'PHP',
  JAVA: 'Java',
  PYTHON: 'Python',
  C: 'C',
  C_PLUS_PLUS: 'C++',
  C_SHARP: 'C#',
  RUBY: 'Ruby',
  SWIFT: 'Swift',
  ANDROID: 'Android',
  IOS: 'iOS',
  FLUTTER: 'Flutter',
  DART: 'Dart',
  RUST: 'Rust',
  GO: 'Go',
  KOTLIN: 'Kotlin',
  GRAPHQL: 'GraphQL',
  APOLLO: 'Apollo',
  NEXTJS: 'NextJS',
  VUEJS: 'VueJS',
  ANGULAR: 'Angular',
  LARAVEL: 'Laravel',
  DJANGO: 'Django',
  SPRING: 'Spring',
  BOOTSTRAP: 'Bootstrap',
  TAILWIND: 'Tailwind',
  MATERIAL_UI: 'Material UI',
  SASS: 'Sass',
  LESS: 'Less',
  STYLED_COMPONENTS: 'Styled Components',
  JQUERY: 'jQuery',
  VUETIFY: 'Vuetify',
  ANT_DESIGN: 'Ant Design',
  CHARTJS: 'ChartJS',
  D3JS: 'D3JS',
  THREEJS: 'ThreeJS',
  WEBGL: 'WebGL',
  UNITY: 'Unity',
  UNREAL: 'Unreal',
  PHASER: 'Phaser',
  GODOT: 'Godot',
  CRYENGINE: 'CryEngine',
  OPENGL: 'OpenGL',
  VULKAN: 'Vulkan',
  DIRECTX: 'DirectX',
  OPENCV: 'OpenCV',
  PYTORCH: 'PyTorch',
  TENSORFLOW: 'TensorFlow',
  KERAS: 'Keras',
  SCIKIT_LEARN: 'Scikit-Learn',
  PANDAS: 'Pandas',
  NUMPY: 'NumPy',
  MATPLOTLIB: 'Matplotlib',
  SELENIUM: 'Selenium',
  JEST: 'Jest',
  CYPRESS: 'Cypress',
  MOCHA: 'Mocha',
  CHAI: 'Chai',
  JASMINE: 'Jasmine',
  ENZYME: 'Enzyme',
  PUPPETEER: 'Puppeteer',
  PROTRACTOR: 'Protractor',
  JUNIT: 'JUnit',
};
