export enum Gender {
  Male,
  Female,
  Other,
}

export enum UserRoles {
  STUDENT,
  ADMIN,
}

export const StudentMajor: { [key: string]: string } = {
  SOFTWARE_ENGINEERING: 'Software Engineering',
  COMPUTER_SCIENCE: 'Computer Science',
  INFORMATION_TECHNOLOGY: 'Information Technology',
  OTHER: 'Other',
};
export const City: { [key: string]: string } = {
  HA_NOI: 'Ha Noi',
  TP_HCM: 'TP.HCM',
  OTHER: 'Other',
};
export const Language: { [key: string]: string } = {
  VIETNAMESE: 'Vietnamese',
  ENGLISH: 'English',
  JAPANESE: 'Japanese',
  KOREAN: 'Korean',
  RUSSIAN: 'Russian',
  CHINESE: 'Chinese',
  SPANISH: 'Spanish',
};
export const Skills: { [key: string]: string } = {
  HTML: 'HTML',
  CSS: 'CSS',
  JAVASCRIPT: 'JavaScript',
  TYPESCRIPT: 'TypeScript',
  REACTJS: 'ReactJS',
  REACT_NATIVE: 'React Native',
  NODEJS: 'NodeJS',
  EXPRESSJS: 'ExpressJS',
  MONGODB: 'MongoDB',
  MYSQL: 'MySQL',
  POSTGRESQL: 'PostgreSQL',
  PHP: 'PHP',
  JAVA: 'Java',
  PYTHON: 'Python',
  C: 'C',
  C_PLUS_PLUS: 'C++',
  C_SHARP: 'C#',
  RUBY: 'Ruby',
  SWIFT: 'Swift',
  ANDROID: 'Android',
  IOS: 'iOS',
  FLUTTER: 'Flutter',
  DART: 'Dart',
  RUST: 'Rust',
  GO: 'Go',
  KOTLIN: 'Kotlin',
  GRAPHQL: 'GraphQL',
  APOLLO: 'Apollo',
  NEXTJS: 'NextJS',
  VUEJS: 'VueJS',
  ANGULAR: 'Angular',
  LARAVEL: 'Laravel',
  DJANGO: 'Django',
  SPRING: 'Spring',
  BOOTSTRAP: 'Bootstrap',
  TAILWIND: 'Tailwind',
  MATERIAL_UI: 'Material UI',
  SASS: 'Sass',
  LESS: 'Less',
  STYLED_COMPONENTS: 'Styled Components',
  JQUERY: 'jQuery',
  VUETIFY: 'Vuetify',
  ANT_DESIGN: 'Ant Design',
  CHARTJS: 'ChartJS',
  D3JS: 'D3JS',
  THREEJS: 'ThreeJS',
  WEBGL: 'WebGL',
  UNITY: 'Unity',
  UNREAL: 'Unreal',
  PHASER: 'Phaser',
  GODOT: 'Godot',
  CRYENGINE: 'CryEngine',
  OPENGL: 'OpenGL',
  VULKAN: 'Vulkan',
  DIRECTX: 'DirectX',
  OPENCV: 'OpenCV',
  PYTORCH: 'PyTorch',
  TENSORFLOW: 'TensorFlow',
  KERAS: 'Keras',
  SCIKIT_LEARN: 'Scikit-Learn',
  PANDAS: 'Pandas',
  NUMPY: 'NumPy',
  MATPLOTLIB: 'Matplotlib',
  SELENIUM: 'Selenium',
  JEST: 'Jest',
  CYPRESS: 'Cypress',
  MOCHA: 'Mocha',
  CHAI: 'Chai',
  JASMINE: 'Jasmine',
  ENZYME: 'Enzyme',
  PUPPETEER: 'Puppeteer',
  PROTRACTOR: 'Protractor',
  JUNIT: 'JUnit',
};
